version: '2'
services:
  tokenplugin-postgresql:
    image: postgres:10.4
    # volumes:
    #     - ~/volumes/jhipster/tokenPlugin/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tokenPlugin
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
